
stages:
  - build-client
  - build-server
  - deploy-lambda

build-client:
    image: node:8.1.0
    stage: build-client
    script:
      - yarn
      - yarn dist
    artifacts:
      paths:
        - ./TorrentChain.Lambda/wwwroot/

build-server:
    image : microsoft/dotnet:latest
    stage: build-server
    script:
      - "cd ./TorrentChain.Lambda"
      - "dotnet build"

deploy-lambda:
    image: node:8.1.0
    stage: deploy-lambda
    script:
      - yarn install serverless -g
      - serverless deploy