
stages:
  - build-client
  - build-server

build-client:
    image: node:8.1.0
    stage: build-client
    script: "yarn build"

build-server:
    image : microsoft/dotnet:latest
    stage: build-server
    script:
      - "cd ./TorrentChain.Lambda"
      - "dotnet build"

