// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoModels.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ProtoModels.proto</summary>
public static partial class ProtoModelsReflection {

  #region Descriptor
  /// <summary>File descriptor for ProtoModels.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ProtoModelsReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFQcm90b01vZGVscy5wcm90byJ4CgpQcm90b0Jsb2NrEg0KBUluZGV4GAEg",
          "ASgDEhEKCUJsb2NrRGF0YRgCIAEoDBIMCgRIYXNoGAMgASgMEhQKDFByZXZp",
          "b3VzSGFzaBgEIAEoDBIRCglTaWduYXR1cmUYBSABKAwSEQoJVGltZVN0YW1w",
          "GAYgASgDYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ProtoBlock), global::ProtoBlock.Parser, new[]{ "Index", "BlockData", "Hash", "PreviousHash", "Signature", "TimeStamp" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ProtoBlock : pb::IMessage<ProtoBlock> {
  private static readonly pb::MessageParser<ProtoBlock> _parser = new pb::MessageParser<ProtoBlock>(() => new ProtoBlock());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ProtoBlock> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ProtoModelsReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoBlock() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoBlock(ProtoBlock other) : this() {
    index_ = other.index_;
    blockData_ = other.blockData_;
    hash_ = other.hash_;
    previousHash_ = other.previousHash_;
    signature_ = other.signature_;
    timeStamp_ = other.timeStamp_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ProtoBlock Clone() {
    return new ProtoBlock(this);
  }

  /// <summary>Field number for the "Index" field.</summary>
  public const int IndexFieldNumber = 1;
  private long index_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long Index {
    get { return index_; }
    set {
      index_ = value;
    }
  }

  /// <summary>Field number for the "BlockData" field.</summary>
  public const int BlockDataFieldNumber = 2;
  private pb::ByteString blockData_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString BlockData {
    get { return blockData_; }
    set {
      blockData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Hash" field.</summary>
  public const int HashFieldNumber = 3;
  private pb::ByteString hash_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString Hash {
    get { return hash_; }
    set {
      hash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "PreviousHash" field.</summary>
  public const int PreviousHashFieldNumber = 4;
  private pb::ByteString previousHash_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString PreviousHash {
    get { return previousHash_; }
    set {
      previousHash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Signature" field.</summary>
  public const int SignatureFieldNumber = 5;
  private pb::ByteString signature_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString Signature {
    get { return signature_; }
    set {
      signature_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "TimeStamp" field.</summary>
  public const int TimeStampFieldNumber = 6;
  private long timeStamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long TimeStamp {
    get { return timeStamp_; }
    set {
      timeStamp_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ProtoBlock);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ProtoBlock other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Index != other.Index) return false;
    if (BlockData != other.BlockData) return false;
    if (Hash != other.Hash) return false;
    if (PreviousHash != other.PreviousHash) return false;
    if (Signature != other.Signature) return false;
    if (TimeStamp != other.TimeStamp) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Index != 0L) hash ^= Index.GetHashCode();
    if (BlockData.Length != 0) hash ^= BlockData.GetHashCode();
    if (Hash.Length != 0) hash ^= Hash.GetHashCode();
    if (PreviousHash.Length != 0) hash ^= PreviousHash.GetHashCode();
    if (Signature.Length != 0) hash ^= Signature.GetHashCode();
    if (TimeStamp != 0L) hash ^= TimeStamp.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Index != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Index);
    }
    if (BlockData.Length != 0) {
      output.WriteRawTag(18);
      output.WriteBytes(BlockData);
    }
    if (Hash.Length != 0) {
      output.WriteRawTag(26);
      output.WriteBytes(Hash);
    }
    if (PreviousHash.Length != 0) {
      output.WriteRawTag(34);
      output.WriteBytes(PreviousHash);
    }
    if (Signature.Length != 0) {
      output.WriteRawTag(42);
      output.WriteBytes(Signature);
    }
    if (TimeStamp != 0L) {
      output.WriteRawTag(48);
      output.WriteInt64(TimeStamp);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Index != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Index);
    }
    if (BlockData.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(BlockData);
    }
    if (Hash.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Hash);
    }
    if (PreviousHash.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(PreviousHash);
    }
    if (Signature.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Signature);
    }
    if (TimeStamp != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(TimeStamp);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ProtoBlock other) {
    if (other == null) {
      return;
    }
    if (other.Index != 0L) {
      Index = other.Index;
    }
    if (other.BlockData.Length != 0) {
      BlockData = other.BlockData;
    }
    if (other.Hash.Length != 0) {
      Hash = other.Hash;
    }
    if (other.PreviousHash.Length != 0) {
      PreviousHash = other.PreviousHash;
    }
    if (other.Signature.Length != 0) {
      Signature = other.Signature;
    }
    if (other.TimeStamp != 0L) {
      TimeStamp = other.TimeStamp;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 8: {
          Index = input.ReadInt64();
          break;
        }
        case 18: {
          BlockData = input.ReadBytes();
          break;
        }
        case 26: {
          Hash = input.ReadBytes();
          break;
        }
        case 34: {
          PreviousHash = input.ReadBytes();
          break;
        }
        case 42: {
          Signature = input.ReadBytes();
          break;
        }
        case 48: {
          TimeStamp = input.ReadInt64();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
